Support Windows Server 2022 CI builds
G-Research/ParquetSharp pull request #258
Opened 2022-02-24 05:11 UTC by adamreeve

GitHub has started rolling out Windows Server 2022 to GitHub actions jobs running on `windows-latest`: https://github.blog/changelog/2022-01-11-github-actions-jobs-running-on-windows-latest-are-now-running-on-windows-server-2022/

This image includes Visual Studio 2022 instead of 2019, so I've updated the build script to expect VS 2022, and explicitly set the Windows image to windows-2022 in the CI configuration so we're pinned to one version rather than randomly getting either 2019 or 2022 during the roll out.

Alternatively we could just stick with 2019, but I think it's best to keep up to date.

2022-02-24 08:38 UTC, marcin-krystianc approved these changes

2022-02-24 12:01 UTC, jgiannuzzi requested changes
I wholeheartedly agree with keeping up to date, thanks @adamreeve!

We should also update the [Building section of the README](https://github.com/G-Research/ParquetSharp#building) to VS 2022, otherwise LGTM 👍

2022-02-24 21:15 UTC, adamreeve commented
Ah good catch thanks Jonathan, I missed that. I've updated the README now.

2022-02-25 07:06 UTC, jgiannuzzi approved these changes

2022-02-25 07:37 UTC, merged